GAMES = [
    {
        "name": "Among Us",
        "genre": "Social Deduction",
        "platforms": "Mobile, PC, Switch",
        "image": "image/amongus.jpg",
        "tag": "Party Pick",
        "description": "Quick rounds, surprise betrayals, and a style that turns every lobby into a story.",
    },
    {
        "name": "Free Fire",
        "genre": "Battle Royale",
        "platforms": "Mobile",
        "image": "image/freefire.jpg",
        "tag": "Fast Match",
        "description": "A high-speed survival shooter built for short sessions and sharp decision making.",
    },
    {
        "name": "Clash of Clans",
        "genre": "Strategy",
        "platforms": "Mobile",
        "image": "image/clashofclans.jpg",
        "tag": "Tactical",
        "description": "Base building, troop planning, and clan teamwork keep every upgrade feeling meaningful.",
    },
    {
        "name": "Forza Horizon",
        "genre": "Racing",
        "platforms": "Xbox, PC",
        "image": "image/forza.jpg",
        "tag": "Open Road",
        "description": "A stylish racing world filled with polished handling, speed festivals, and scenic routes.",
    },
    {
        "name": "Minecraft",
        "genre": "Sandbox",
        "platforms": "Everywhere",
        "image": "image/minecraft.png",
        "tag": "Creative",
        "description": "Build quietly, survive boldly, or invent something strange with total freedom.",
    },
    {
        "name": "Uncharted",
        "genre": "Action Adventure",
        "platforms": "PlayStation, PC",
        "image": "image/uncharted.jpg",
        "tag": "Story Rich",
        "description": "Cinematic set pieces and treasure-hunting momentum make it a go-to adventure series.",
    },
    {
        "name": "WWE 2K",
        "genre": "Sports Entertainment",
        "platforms": "PlayStation, Xbox, PC",
        "image": "image/wwe2k.jpg",
        "tag": "Showtime",
        "description": "Big entrances, rivalry drama, and over-the-top match energy built for fans of spectacle.",
    },
    {
        "name": "Grand Theft Auto",
        "genre": "Open World",
        "platforms": "PlayStation, Xbox, PC",
        "image": "image/grandtheftauto.jpg",
        "tag": "Iconic",
        "description": "A city-sized playground for missions, chaos, satire, and endless player stories.",
    },
    {
        "name": "Valorant",
        "genre": "Tactical Shooter",
        "platforms": "PC, Console",
        "image": "image/valorant.png",
        "tag": "Precision",
        "description": "Sharp teamplay, hero abilities, and tight maps make every round feel high pressure.",
    },
    {
        "name": "Elden Ring",
        "genre": "Action RPG",
        "platforms": "PlayStation, Xbox, PC",
        "image": "image/eldenring.jpg",
        "tag": "Epic",
        "description": "A vast fantasy world filled with looming castles, mystery, and hard-fought victories.",
    },
    {
        "name": "Cyberpunk 2077",
        "genre": "Sci-Fi RPG",
        "platforms": "PlayStation, Xbox, PC",
        "image": "image/cyberpunk2077.jpg",
        "tag": "Neon",
        "description": "Night City glows with chrome, rain, and endless stories around every street corner.",
    },
    {
        "name": "Red Dead Redemption 2",
        "genre": "Western Adventure",
        "platforms": "PlayStation, Xbox, PC",
        "image": "image/reddeadredemption2.jpg",
        "tag": "Frontier",
        "description": "Sweeping landscapes and quiet campfire moments give this outlaw world unusual depth.",
    },
    {
        "name": "Assassin's Creed Mirage",
        "genre": "Stealth Action",
        "platforms": "PlayStation, Xbox, PC",
        "image": "image/assassinscreedmirage.jpg",
        "tag": "Stealth",
        "description": "Rooftop chases, hidden blades, and historic city streets keep the series identity intact.",
    },
    {
        "name": "God of War Ragnarok",
        "genre": "Mythic Action",
        "platforms": "PlayStation",
        "image": "image/godofwarragnarok.jpg",
        "tag": "Mythic",
        "description": "Frozen realms, giant creatures, and intimate father-son drama hit with huge force.",
    },
    {
        "name": "Marvel's Spider-Man 2",
        "genre": "Superhero Action",
        "platforms": "PlayStation",
        "image": "image/marvelsspiderman2.jpg",
        "tag": "Heroic",
        "description": "Fast web-swinging and skyline spectacle keep the city feeling constantly alive.",
    },
    {
        "name": "Halo Infinite",
        "genre": "Sci-Fi Shooter",
        "platforms": "Xbox, PC",
        "image": "image/haloinfinite.jpg",
        "tag": "Arena",
        "description": "Power weapons, ringworld vistas, and classic shooter rhythm give it familiar strength.",
    },
    {
        "name": "Rocket League",
        "genre": "Sports Arcade",
        "platforms": "PlayStation, Xbox, Switch, PC",
        "image": "image/rocketleague.jpg",
        "tag": "Boosted",
        "description": "Cars, aerial goals, and impossible saves make every match a highlight reel.",
    },
    {
        "name": "League of Legends",
        "genre": "MOBA",
        "platforms": "PC",
        "image": "image/leagueoflegends.jpg",
        "tag": "Competitive",
        "description": "Distinct champions and tense late-game team fights give the genre lasting momentum.",
    },
    {
        "name": "EA Sports FC 25",
        "genre": "Football Simulation",
        "platforms": "PlayStation, Xbox, Switch, PC",
        "image": "image/easportsfc25.jpg",
        "tag": "Matchday",
        "description": "Crowd energy, stadium lighting, and fast transitions make every match feel eventful.",
    },
    {
        "name": "PUBG Battlegrounds",
        "genre": "Battle Royale",
        "platforms": "PlayStation, Xbox, PC, Mobile",
        "image": "image/pubg.jpg",
        "tag": "Survival",
        "description": "Long sightlines, tense circles, and tactical looting keep the pressure constant.",
    },
]

ABOUT_SECTIONS = [
    {
        "title": "Wide Selection",
        "description": "The site now covers a much larger mix of shooters, racers, adventures, sports titles, sandboxes, and fantasy worlds.",
    },
    {
        "title": "Image-Driven Layout",
        "description": "Cards, galleries, and hero panels are built around game artwork so the pages feel fuller and more engaging.",
    },
    {
        "title": "Easy to Browse",
        "description": "Each page is focused on browsing games quickly, with clear labels for genre, platform, and highlights.",
    },
]

BLOG_POSTS = [
    {
        "title": "Why Forza Still Feels Effortless",
        "category": "Racing",
        "read_time": "4 min read",
        "image": "image/forza.jpg",
        "excerpt": "Forza keeps its appeal by blending festival energy, approachable controls, and a world that begs to be explored.",
    },
    {
        "title": "Clash of Clans and the Joy of Slow Progress",
        "category": "Strategy",
        "read_time": "5 min read",
        "image": "image/clashofclans.jpg",
        "excerpt": "Strong strategy games make upgrades feel earned, and few mobile titles understand long-term satisfaction like this one.",
    },
    {
        "title": "Minecraft as a Creativity Engine",
        "category": "Sandbox",
        "read_time": "3 min read",
        "image": "image/minecraft.png",
        "excerpt": "Minecraft stays timeless because it gives players just enough rules to build worlds that feel entirely personal.",
    },
    {
        "title": "Among Us Proved Social Games Can Go Massive",
        "category": "Party",
        "read_time": "4 min read",
        "image": "image/amongus.jpg",
        "excerpt": "A tiny core idea became unforgettable because tension, humor, and distrust are powerful ingredients when friends play together.",
    },
    {
        "title": "Elden Ring and the Power of Atmosphere",
        "category": "RPG",
        "read_time": "5 min read",
        "image": "image/eldenring.jpg",
        "excerpt": "Some worlds pull players forward through mystery alone, and few recent adventures use scale and silence as effectively.",
    },
    {
        "title": "Rocket League Is Still the Best Chaos-to-Skill Ratio",
        "category": "Sports Arcade",
        "read_time": "3 min read",
        "image": "image/rocketleague.jpg",
        "excerpt": "The rules are simple, the ceiling is absurd, and that combination keeps the game endlessly watchable.",
    },
]

CONTACT_CHANNELS = [
    {
        "title": "General Questions",
        "value": "hello@gamezone.demo",
        "description": "Use the form if you want to share feedback about the design or layout.",
    },
    {
        "title": "Collaboration",
        "value": "projects@gamezone.demo",
        "description": "Good for portfolio discussions, showcase ideas, or static page improvements.",
    },
    {
        "title": "Response Style",
        "value": "Demo contact only",
        "description": "This project validates the form in Django, but it does not store or send messages anywhere.",
    },
]

FAQS = [
    {
        "question": "Is this a full gaming platform?",
        "answer": "No. It is intentionally a clean Django website project with static content and polished presentation.",
    },
    {
        "question": "Does the contact form save data?",
        "answer": "No. The form only validates input and shows a success state so the project stays backend-light.",
    },
    {
        "question": "Can more pages be added later?",
        "answer": "Yes. The content structure now makes it much easier to extend the site with new sections or templates.",
    },
]
